### ISSUE TITLE
Fehler bei der Ausführung - line 47

### ISSUE THREAD

**Issue by tobiaskl93** [MrKrisKrisu/Hochschule-Hannover-Pruefungsergebnischecker#3]
System: OSX Big Sur, aktuellste Python-Version 3.9.6

Bekomme bei der Ausführung den folgenden Fehler:

Rufe Startseite auf
Einloggen...
Traceback (most recent call last):
  File "/Users/XXXXXXXXX/Downloads/HISinOne-QIS-exam-notification-master/crawl.py", line 47, in <module>
    link_notenspiegel = re.search('<a href="(.+?)" class="regular">Notenspiegel</a>', result.content).group(1)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
>>>

**Comment by MrKrisKrisu** [comment]
Das Skript ist jetzt mit Python3 kompatibel! :) (See #6)
